### ISSUE TITLE
[PRE REVIEW]: responder test

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#102]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal1
**Branch with paper.md** (empty if default branch): 
**Version:** v1
**Editor:** @max-anu
**Reviewers:** @max-anu
**Managing EiC:** Max Proft

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8)
```

**Author instructions**

Thanks for submitting your recipe to medportal @max-anu. **Currently, there isn't a medportal editor assigned** to your recipe.

The AEiC suggestion for the handling editor is @max-anu.

@max-anu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). You can search [the list of people](https://reviewers.medportal-dev-6a745f452687.herokuapp.com/lookup) that have already agreed to review and may be suitable for this submission.

**Editor instructions**

The medportal submission bot @med-oc is here to help you find and assign reviewers and start the main review. To find out what @med-oc can do for you type:

```
@med-oc commands
```

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the [https://github.com/max-anu/example-medportal1](https://github.com/max-anu/example-medportal1)?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@max-anu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)
- [ ] **Data sharing:** If the paper contains original data, data are accessible to the reviewers. If the paper contains no original data, please check this item.
- [ ] **Reproducibility:** If the paper contains original results, results are entirely reproducible by reviewers. If the paper contains no original results, please check this item.
- [ ] **Human and animal research:** If the paper contains original data research on humans subjects or animals, does it comply with [JOSS's human participants research policy and/or animal research policy](https://joss.readthedocs.io/en/latest/policies.html?highlight=animal#joss-policies)? If the paper contains no such data, please check this item.

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need**: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Does the paper have a section titled 'Statement of need' that clearly states what problems the software is designed to solve, who the target audience is, and its relation to other work?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://pandoc.org/MANUAL.html#extension-citations)?

**Comment by med-oc** [comment]
Hello humans, I'm @med-oc, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@med-oc help
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@med-oc generate pdf
```

**Comment by max-anu** [comment]
@med-oc add assignee: @max-anu

**Comment by med-oc** [comment]
@max-anu added as assignee.

**Comment by max-anu** [comment]
@med-oc remove assignee: @max-anu

**Comment by med-oc** [comment]
@max-anu removed from assignees.

**Comment by max-anu** [comment]
@med-oc add assignee: @max-anu

**Comment by med-oc** [comment]
@max-anu added as assignee.

**Comment by max-anu** [comment]
@med-oc add checklist for @max-anu

**Comment by med-oc** [comment]
Checklist added for @max-anu

**Comment by max-anu** [comment]
@med-oc add checklist for @max-anu

**Comment by med-oc** [comment]
There is already a checklist for @max-anu

**Comment by max-anu** [comment]
@med-oc remove checklist for @max-anu

**Comment by med-oc** [comment]
Checklist for @max-anu removed

**Comment by max-anu** [comment]
@med-oc add checklist for @max-anu

**Comment by med-oc** [comment]
Checklist added for @max-anu

**Comment by max-anu** [comment]
@med-oc  assign me as editor

**Comment by max-anu** [comment]
@med-oc assign @max-anu as editor

**Comment by med-oc** [comment]
Assigned! @max-anu is now the editor

**Comment by max-anu** [comment]
@med-oc code of conduct

**Comment by med-oc** [comment]
Our CoC: https://github.com/openjournals/joss/blob/master/CODE_OF_CONDUCT.md

**Comment by med-oc** [comment]
It's adapted from the Contributor Covenant: http://contributor-covenant.org

**Comment by med-oc** [comment]
Reports of abusive or harassing behavior may be reported to reports@theoj.org

**Comment by max-anu** [comment]
@med-oc check references

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc start review

**Comment by med-oc** [comment]
Can't start a review without reviewers

**Comment by max-anu** [comment]
@med-oc add @max-anu as reviewer

**Comment by med-oc** [comment]
@max-anu added to the reviewers list!

**Comment by max-anu** [comment]
@med-oc remove @max-anu from reviewers

**Comment by med-oc** [comment]
@max-anu removed from the reviewers list!

**Comment by max-anu** [comment]
@med-oc add @max-anu as reviewer

**Comment by med-oc** [comment]
@max-anu added to the reviewers list!

**Comment by max-anu** [comment]
@med-oc start review

**Comment by med-oc** [comment]
OK, I've started the review over in https://github.com/ACCESS-NRI/med-reviews/issues/103.
