### ISSUE TITLE
[REVIEW]: responder test

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#103]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal1
**Branch with paper.md** (empty if default branch): 
**Version:** v2.1.3 a
**Editor:** @max-anu
**Reviewers:** @max-anu
**Archive:** 10.21105/medportal.00103

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/696010b623ad0751d58e31d512ad5ff8)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/max-anu/example-medportal1" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@max-anu, your review will be checklist based. Each of you will have a separate checklist that you should update when carrying out your review.
First of all you need to run this command in a separate comment to create the checklist:

```
@med-oc generate my checklist
```

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @max-anu know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Checklists

📝 [Checklist for @max-anu](https://github.com/ACCESS-NRI/med-reviews/issues/103#issuecomment-1749787906)

**Comment by med-oc** [comment]
Hello humans, I'm @med-oc, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@med-oc help
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@med-oc generate pdf
```

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by med-oc** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00103/medportal.00103/10.21105.medportal.00103.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/ACCESS-NRI/med-recipes/blob/medportal.00103/medportal.00103/10.21105.medportal.00103.pdf) :page_facing_up: :point_left:

**Comment by max-anu** [comment]
Hello @med-oc

**Comment by med-oc** [comment]
Hi!

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Add to this issue's reviewers list
@med-oc add @username as reviewer

# Remove from this issue's reviewers list
@med-oc remove @username from reviewers

# Assign a user as the editor of this submission
@med-oc assign @username as editor

# Remove the editor assigned to this submission
@med-oc remove editor

# Send an invitation to a user to collaborate in the review
@med-oc invite @username

# Add a user to this issue's assignees list
@med-oc add assignee: @username

# Remove a user from this issue's assignees list
@med-oc remove assignee: @username

# Replies to 'list editors'
@med-oc list editors

# Set a value for version
@med-oc set v1.0.0 as version

# Set a value for archive
@med-oc set 10.21105/medportal.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@med-oc review successful

# Label issue with: recommend rejection
@med-oc review failed

# Close the issue
@med-oc reject

# Add review checklist for a user
@med-oc add checklist for @username

# Remove the checklist for a user
@med-oc remove checklist for @username

# Generates the pdf paper
@med-oc generate pdf

# Recommends the submission for acceptance
@med-oc recommend-accept

# Accept and publish the paper
@med-oc accept

# Generates a LaTeX preprint file
@med-oc generate preprint

# Open the review issue
@med-oc start review

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by max-anu** [comment]
@med-oc list editors

**Comment by med-oc** [comment]
Current recipe editors

```
@AndyHoggANU
@CodeGat
@MartinDix
@NBateman-bit
@OKaluza
@Quartzer2
@SeanBryan51
@aidanheerdegen
@anton-seaice
@atteggiani
@bschroeter
@ccarouge
@dougiesquire
@echus
@ezhilsabareesh8
@flicj191
@harshula
@headmetal
@heidinett
@jo-basevi
@kdruken
@kieranricardo
@max-anu
@med-oc
@penguian
@rbeucher
@rogeredberg
@svenbuder
@utkarshgupta95
```

**Comment by max-anu** [comment]
@med-oc remove editor

**Comment by med-oc** [comment]
Editor removed!

**Comment by max-anu** [comment]
@med-oc add @max-anu as editor

**Comment by med-oc** [comment]
Assigned! @max-anu is now the editor

**Comment by max-anu** [comment]
@med-oc check repository

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc generate my checklist

**Comment by max-anu** [comment]
@med-oc set version as v2.1.3 a

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc set v2.1.3 a as version

**Comment by med-oc** [comment]
Done! version is now v2.1.3 a

**Comment by max-anu** [comment]
@med-oc set 10.21105/medportal.00103 as archive

**Comment by med-oc** [comment]
Done! archive is now 10.21105/medportal.00103

**Comment by max-anu** [comment]
@med-oc thanks

**Comment by med-oc** [comment]
You are welcome

**Comment by max-anu** [comment]
@med-oc abldifadj

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc reject
