### ISSUE TITLE
[PRE REVIEW]: other buffy

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#106]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal3
**Branch with paper.md** (empty if default branch): 
**Version:** v1
**Editor:** @max-anu
**Reviewers:** @max-anu
**Managing EiC:** Max Proft

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/4e703f98739f934d3aa5cb158c3457d4/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/4e703f98739f934d3aa5cb158c3457d4)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/4e703f98739f934d3aa5cb158c3457d4"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/4e703f98739f934d3aa5cb158c3457d4/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/4e703f98739f934d3aa5cb158c3457d4/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/4e703f98739f934d3aa5cb158c3457d4)
```

**Author instructions**

Thanks for submitting your recipe to medportal @max-anu. **Currently, there isn't a medportal editor assigned** to your recipe.

The AEiC suggestion for the handling editor is @max-anu.

@max-anu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). You can search [the list of people](https://reviewers.medportal-dev-6a745f452687.herokuapp.com/lookup) that have already agreed to review and may be suitable for this submission.

**Editor instructions**

The medportal submission bot @med-oc is here to help you find and assign reviewers and start the main review. To find out what @med-oc can do for you type:

```
@med-oc commands
```

**Comment by med-oc** [comment]
Hello humans, I'm @med-oc, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@med-oc help
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@med-oc generate pdf
```

**Comment by max-anu** [comment]
@med-oc check references

**Comment by med-oc** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1371/journal.pcbi.1009149 is OK
- 10.25080/majora-212e5952-00e is OK
- 10.1596/978-1-4648-1523-2_ch13 is OK
- 10.12688/gatesopenres.13031.2 is OK
- 10.1186/s12889-018-5294-z is OK
- 10.1371/journal.pcbi.1009255 is OK
- 10.1371/journal.pone.0260247 is OK
- 10.1371/journal.pcbi.1008316 is OK
- 10.1093/femspd/ftz006 is OK
- 10.1038/s41592-018-0235-4 is OK
- 10.1093/bioinformatics/bty407 is OK
- 10.21105/joss.03021 is OK
- 10.21105/joss.03262 is OK
- 10.21105/joss.01891 is OK
- 10.1038/s41592-018-0137-5 is OK
- 10.21105/joss.01026 is OK
- 10.3389/fninf.2017.00069 is OK
- 10.1109/mcse.2011.35 is OK
- 10.21105/joss.01450 is OK
- 10.1038/d41586-020-02462-7 is OK
- 10.25080/Majora-7b98e3ed-013 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by max-anu** [comment]
@med-oc invite @max-anu

**Comment by med-oc** [comment]
@max-anu already has access.

**Comment by max-anu** [comment]
@med-oc invite @rhaegar325

**Comment by med-oc** [comment]
@rhaegar325 already has access.

**Comment by max-anu** [comment]
@med-oc check repository

**Comment by med-oc** [comment]
```
Software report:

github.com/AlDanial/cloc v 1.88  T=0.01 s (466.5 files/s, 71378.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              1             55              0            280
Markdown                         2             56              0            144
Jupyter Notebook                 1              0             74              3
-------------------------------------------------------------------------------
SUM:                             4            111             74            427
-------------------------------------------------------------------------------


gitinspector failed to run statistical information for the repository
```

**Comment by med-oc** [comment]
Wordcount for `paper.md` is 2619

**Comment by med-oc** [comment]
Failed to discover a valid open source license

**Comment by max-anu** [comment]
@med-oc create post-review checklist

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc create post-review checklist

**Comment by med-oc** [comment]
This is not a review issue

**Comment by max-anu** [comment]
@med-oc add @max-anu as reviewer

**Comment by med-oc** [comment]
@max-anu added to the reviewers list!

**Comment by max-anu** [comment]
@med-oc assign @max-anu as editor

**Comment by med-oc** [comment]
Assigned! @max-anu is now the editor

**Comment by max-anu** [comment]
@med-oc start review

**Comment by med-oc** [comment]
OK, I've started the review over in https://github.com/ACCESS-NRI/med-reviews/issues/107.
