### ISSUE TITLE
[REVIEW]: New Token test

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#109]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal2
**Branch with paper.md** (empty if default branch): 
**Version:** v1
**Editor:** @max-anu
**Reviewers:** @max-anu
**Archive:** 10.21105/medportal.00109

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/3f1ae28d4cbcb81ee9e3c8ae45356b32/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/3f1ae28d4cbcb81ee9e3c8ae45356b32)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/3f1ae28d4cbcb81ee9e3c8ae45356b32"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/3f1ae28d4cbcb81ee9e3c8ae45356b32/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/3f1ae28d4cbcb81ee9e3c8ae45356b32/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/3f1ae28d4cbcb81ee9e3c8ae45356b32)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/max-anu/example-medportal2" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@max-anu, your review will be checklist based. Each of you will have a separate checklist that you should update when carrying out your review.
First of all you need to run this command in a separate comment to create the checklist:

```
@med-oc generate my checklist
```

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @max-anu know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Checklists

  @max-anu, please create your checklist typing: `@med-oc generate my checklist`

**Comment by max-anu** [comment]
@med-oc accept

**Comment by med-oc** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by med-oc** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.0109/status.svg)](https://doi.org/10.21105/joss.0109)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.0109">
  <img src="https://joss.theoj.org/papers/10.21105/joss.0109/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.0109/status.svg
   :target: https://doi.org/10.21105/joss.0109
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.0109/status.svg)](https://doi.org/10.21105/joss.0109)

**We need your help!**

The Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://reviewers.joss.theoj.org/join
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
