### ISSUE TITLE
[PRE REVIEW]: Example Medportal 3

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#11]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal3
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @max-anu
**Reviewers:** @max-anu
**Managing EiC:** Max Proft

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/bc63b3b379147c8a0f2f21344fc5bd74/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/bc63b3b379147c8a0f2f21344fc5bd74)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/bc63b3b379147c8a0f2f21344fc5bd74"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/bc63b3b379147c8a0f2f21344fc5bd74/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/bc63b3b379147c8a0f2f21344fc5bd74/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/bc63b3b379147c8a0f2f21344fc5bd74)
```

**Author instructions**

Thanks for submitting your recipe to ACCESS @max-anu. **Currently, there isn't a ACCESS editor assigned** to your recipe.

The AEiC suggestion for the handling editor is @max-anu.

@max-anu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). You can search [the list of people](https://reviewers.medportal-dev-6a745f452687.herokuapp.com/lookup) that have already agreed to review and may be suitable for this submission.

**Editor instructions**

The ACCESS submission bot @med-oc is here to help you find and assign reviewers and start the main review. To find out what @med-oc can do for you type:

```
@med-oc commands
```

**Comment by med-oc** [comment]
Hello humans, I'm @med-oc, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@med-oc help
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@med-oc generate pdf
```

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Add to this issue's reviewers list
@med-oc add @username as reviewer

# Remove from this issue's reviewers list
@med-oc remove @username from reviewers

# Assign a user as the editor of this submission
@med-oc assign @username as editor

# Remove the editor assigned to this submission
@med-oc remove editor

# Send an invitation to a user to collaborate in the review
@med-oc invite @username

# Add a user to this issue's assignees list
@med-oc add assignee: @username

# Remove a user from this issue's assignees list
@med-oc remove assignee: @username

# Replies to 'list editors'
@med-oc list editors

# Set a value for version
@med-oc set v1.0.0 as version

# Set a value for archive
@med-oc set 10.21105/joss.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@med-oc review successful

# Label issue with: recommend rejection
@med-oc review failed

# Close the issue
@med-oc reject

# Add review checklist for a user
@med-oc add checklist for @username

# Remove the checklist for a user
@med-oc remove checklist for @username

# Generates the pdf paper
@med-oc generate pdf

# Recommends the submission for acceptance
@med-oc recommend-accept

# Accept and publish the paper
@med-oc accept

# Generates a LaTeX preprint file
@med-oc generate preprint

# Open the review issue
@med-oc start review

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by max-anu** [comment]
@med-oc add @max-anu as reviewer

**Comment by med-oc** [comment]
@max-anu added to the reviewers list!

**Comment by max-anu** [comment]
@med-oc assign @max-anu as editor

**Comment by max-anu** [comment]
@med-oc review successful

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by med-oc** [comment]
:wave: @openjournals/mt-eics, this paper is ready to be accepted and published.

Check final proof :point_right::page_facing_up: [Download article](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00011/medportal.00011/10.21105.medportal.00011.pdf)

If the paper PDF and the deposit XML files look good in https://github.com/ACCESS-NRI/med-recipes/pull/14, then you can now move forward with accepting the submission by compiling again with the command `@editorialbot accept`

**Comment by max-anu** [comment]
@med-oc accept

**Comment by med-oc** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by med-oc** [comment]
:warning: Couldn't acccept/publish paper. [An error happened](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5897615006?check_suite_focus=true). Could not deposit with Open Journals.

**Comment by max-anu** [comment]
@med-oc start review

**Comment by med-oc** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/12.
