### ISSUE TITLE
[PRE REVIEW]: Example3 - Good DOI

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#13]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal2
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.2
**Editor:** @max-anu
**Reviewers:** @max-anu
**Managing EiC:** Max Proft

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/d0e6d00f1ed32952402a1f8e731759e2/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/d0e6d00f1ed32952402a1f8e731759e2)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/d0e6d00f1ed32952402a1f8e731759e2"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/d0e6d00f1ed32952402a1f8e731759e2/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/d0e6d00f1ed32952402a1f8e731759e2/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/d0e6d00f1ed32952402a1f8e731759e2)
```

**Author instructions**

Thanks for submitting your recipe to medportal @max-anu. **Currently, there isn't a medportal editor assigned** to your recipe.

The AEiC suggestion for the handling editor is @max-anu.

@max-anu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). You can search [the list of people](https://reviewers.medportal-dev-6a745f452687.herokuapp.com/lookup) that have already agreed to review and may be suitable for this submission.

**Editor instructions**

The medportal submission bot @med-oc is here to help you find and assign reviewers and start the main review. To find out what @med-oc can do for you type:

```
@med-oc commands
```

**Comment by med-oc** [comment]
Hello humans, I'm @med-oc, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@med-oc help
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@med-oc generate pdf
```

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Add to this issue's reviewers list
@med-oc add @username as reviewer

# Remove from this issue's reviewers list
@med-oc remove @username from reviewers

# Assign a user as the editor of this submission
@med-oc assign @username as editor

# Remove the editor assigned to this submission
@med-oc remove editor

# Send an invitation to a user to collaborate in the review
@med-oc invite @username

# Add a user to this issue's assignees list
@med-oc add assignee: @username

# Remove a user from this issue's assignees list
@med-oc remove assignee: @username

# Replies to 'list editors'
@med-oc list editors

# Set a value for version
@med-oc set v1.0.0 as version

# Set a value for archive
@med-oc set 10.21105/joss.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@med-oc review successful

# Label issue with: recommend rejection
@med-oc review failed

# Close the issue
@med-oc reject

# Add review checklist for a user
@med-oc add checklist for @username

# Remove the checklist for a user
@med-oc remove checklist for @username

# Generates the pdf paper
@med-oc generate pdf

# Recommends the submission for acceptance
@med-oc recommend-accept

# Accept and publish the paper
@med-oc accept

# Generates a LaTeX preprint file
@med-oc generate preprint

# Open the review issue
@med-oc start review

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by max-anu** [comment]
@med-oc start review

**Comment by med-oc** [comment]
Can't start a review without reviewers

**Comment by max-anu** [comment]
@med-oc add @max-anu as reviewer

**Comment by med-oc** [comment]
@max-anu added to the reviewers list!

**Comment by max-anu** [comment]
@med-oc assign @max-anu as editor

**Comment by med-oc** [comment]
Assigned! @max-anu is now the editor

**Comment by max-anu** [comment]
@med-oc start review

**Comment by med-oc** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/14.
