### ISSUE TITLE
[PRE REVIEW]: lowercase alias

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#15]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal2
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0
**Editor:** @max-anu
**Reviewers:** @max-anu
**Managing EiC:** Max Proft

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00)
```

**Author instructions**

Thanks for submitting your recipe to medportal @max-anu. **Currently, there isn't a medportal editor assigned** to your recipe.

The AEiC suggestion for the handling editor is @max-anu.

@max-anu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). You can search [the list of people](https://reviewers.medportal-dev-6a745f452687.herokuapp.com/lookup) that have already agreed to review and may be suitable for this submission.

**Editor instructions**

The medportal submission bot @med-oc is here to help you find and assign reviewers and start the main review. To find out what @med-oc can do for you type:

```
@med-oc commands
```

**Comment by med-oc** [comment]
Hello humans, I'm @med-oc, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@med-oc help
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@med-oc generate pdf
```

**Comment by max-anu** [comment]
@med-oc add @max-anu as reviewer

**Comment by med-oc** [comment]
@max-anu added to the reviewers list!

**Comment by max-anu** [comment]
@med-oc assign @max-anu as editor

**Comment by med-oc** [comment]
Assigned! @max-anu is now the editor

**Comment by max-anu** [comment]
@med-oc start review

**Comment by med-oc** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/16.
