### ISSUE TITLE
[PRE REVIEW]: Real Paper Example 1

### ISSUE THREAD

**Issue by max-anu** [ACCESS-NRI/med-reviews#6]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal1
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0
**Editor:** Pending
**Reviewers:** Pending
**Managing EiC:** Max Proft

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/f04fd0b2bed7677db2b2ca9e96527e6b/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/f04fd0b2bed7677db2b2ca9e96527e6b)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/f04fd0b2bed7677db2b2ca9e96527e6b"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/f04fd0b2bed7677db2b2ca9e96527e6b/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/f04fd0b2bed7677db2b2ca9e96527e6b/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/f04fd0b2bed7677db2b2ca9e96527e6b)
```

**Author instructions**

Thanks for submitting your recipe to ACCESS @max-anu. **Currently, there isn't a ACCESS editor assigned** to your recipe.

The AEiC suggestion for the handling editor is @max-anu.

@max-anu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). You can search [the list of people](https://reviewers.medportal-dev-6a745f452687.herokuapp.com/lookup) that have already agreed to review and may be suitable for this submission.

**Editor instructions**

The ACCESS submission bot @max-anu is here to help you find and assign reviewers and start the main review. To find out what @max-anu can do for you type:

```
@max-anu commands
```

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the [https://github.com/max-anu/example-medportal1](https://github.com/max-anu/example-medportal1)?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@max-anu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)
- [x] **Data sharing:** If the paper contains original data, data are accessible to the reviewers. If the paper contains no original data, please check this item.
- [x] **Reproducibility:** If the paper contains original results, results are entirely reproducible by reviewers. If the paper contains no original results, please check this item.
- [x] **Human and animal research:** If the paper contains original data research on humans subjects or animals, does it comply with [JOSS's human participants research policy and/or animal research policy](https://joss.readthedocs.io/en/latest/policies.html?highlight=animal#joss-policies)? If the paper contains no such data, please check this item.

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need**: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of need' that clearly states what problems the software is designed to solve, who the target audience is, and its relation to other work?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://pandoc.org/MANUAL.html#extension-citations)?

**Comment by max-anu** [comment]
@max-anu generate pdf

**Comment by max-anu** [comment]
Hello @max-anu

**Comment by max-anu** [comment]
@max-anu commands

**Comment by max-anu** [comment]
Hello @max-anu

**Comment by svenbuder** [comment]
Hello @max-anu

**Comment by max-anu** [comment]
Hi!

**Comment by max-anu** [comment]
Hello @med-oc

**Comment by med-oc** [comment]
Hi!

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Replies to 'list editors'
@med-oc list editors

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@med-oc check references
@med-oc check references from branch custom-branch-name

# Perform checks on the repository
# Optionally, it can be run on a non-default branch 
@med-oc check repository
@med-oc check repository from branch custom-branch-name

# Random facts about cats
@med-oc tell me something about cats

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by max-anu** [comment]
@med-oc generate my checklist

**Comment by med-oc** [comment]
@max-anu I can't do that because you are not a reviewer

**Comment by max-anu** [comment]
@med-oc assign @max-anu as editor

**Comment by med-oc** [comment]
I'm sorry @max-anu, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by max-anu** [comment]
@med-oc compile pdf

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc code of conduct

**Comment by med-oc** [comment]
Our CoC: https://github.com/openjournals/joss/blob/master/CODE_OF_CONDUCT.md

**Comment by med-oc** [comment]
It's adapted from the Contributor Covenant: http://contributor-covenant.org

**Comment by med-oc** [comment]
Reports of abusive or harassing behavior may be reported to reports@theoj.org

**Comment by max-anu** [comment]
@med-oc list editors

**Comment by max-anu** [comment]
@med-oc check references

**Comment by max-anu** [comment]
@med-oc check repository

**Comment by max-anu** [comment]
hello @med-oc

**Comment by med-oc** [comment]
Hi!

**Comment by max-anu** [comment]
@med-oc list editors

**Comment by max-anu** [comment]
@med-oc check repository

**Comment by max-anu** [comment]
@med-oc generate my checklist

**Comment by med-oc** [comment]
@max-anu I can't do that because you are not a reviewer

**Comment by max-anu** [comment]
@med-oc check repository

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc hello

**Comment by max-anu** [comment]
@med-oc help

**Comment by max-anu** [comment]
@med-oc thank you

**Comment by max-anu** [comment]
@med-oc test update

**Comment by max-anu** [comment]
@med-oc help

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Replies to 'list editors'
@med-oc list editors

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@med-oc check references
@med-oc check references from branch custom-branch-name

# Perform checks on the repository
# Optionally, it can be run on a non-default branch 
@med-oc check repository
@med-oc check repository from branch custom-branch-name

# Random facts about cats
@med-oc tell me something about cats

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by max-anu** [comment]
@med-oc test update

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc tell me something about cats

**Comment by max-anu** [comment]
@med-oc add checklist for @max-anu

**Comment by med-oc** [comment]
Checklist added for @max-anu

**Comment by max-anu** [comment]
@med-oc remind @max-anu  in 1 day

**Comment by med-oc** [comment]
Reminder set for @max-anu in 1 day

**Comment by max-anu** [comment]
hello @med-oc

**Comment by med-oc** [comment]
Hi!

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc  generate pdf

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf
