### ISSUE TITLE
[PRE REVIEW]: Example 2

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#7]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal1
**Branch with paper.md** (empty if default branch): 
**Version:** v1.2.3
**Editor:** @max-anu
**Reviewers:** @max-anu
**Managing EiC:** Max Proft

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/d7fd4fa1bcf507d45bad0ef420b19242/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/d7fd4fa1bcf507d45bad0ef420b19242)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/d7fd4fa1bcf507d45bad0ef420b19242"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/d7fd4fa1bcf507d45bad0ef420b19242/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/d7fd4fa1bcf507d45bad0ef420b19242/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/d7fd4fa1bcf507d45bad0ef420b19242)
```

**Author instructions**

Thanks for submitting your recipe to ACCESS @max-anu. **Currently, there isn't a ACCESS editor assigned** to your recipe.

@max-anu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). You can search [the list of people](https://reviewers.medportal-dev-6a745f452687.herokuapp.com/lookup) that have already agreed to review and may be suitable for this submission.

**Editor instructions**

The ACCESS submission bot @med-oc is here to help you find and assign reviewers and start the main review. To find out what @med-oc can do for you type:

```
@med-oc commands
```

**Comment by max-anu** [comment]
@med-oc commands

**Comment by max-anu** [comment]
hello @med-oc

**Comment by max-anu** [comment]
hello @med-oc

**Comment by max-anu** [comment]
@med-oc help

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Blah Blah Blah
@med-oc test update

# Add to this issue's reviewers list
@med-oc add @username as reviewer

# Remove from this issue's reviewers list
@med-oc remove @username from reviewers

# Assign a user as the editor of this submission
@med-oc assign @username as editor

# Remove the editor assigned to this submission
@med-oc remove editor

# Send an invitation to a user to collaborate in the review
@med-oc invite @username

# Add a user to this issue's assignees list
@med-oc add assignee: @username

# Remove a user from this issue's assignees list
@med-oc remove assignee: @username

# Replies to 'list editors'
@med-oc list editors

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@med-oc check references
@med-oc check references from branch custom-branch-name

# Perform checks on the repository
# Optionally, it can be run on a non-default branch 
@med-oc check repository
@med-oc check repository from branch custom-branch-name

# Set a value for version
@med-oc set v1.0.0 as version

# Set a value for archive
@med-oc set 10.21105/joss.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@med-oc review successful

# Label issue with: recommend rejection
@med-oc review failed

# Close the issue
@med-oc reject

# Random facts about cats
@med-oc tell me something about cats

# Add review checklist for a user
@med-oc add checklist for @username

# Remove the checklist for a user
@med-oc remove checklist for @username

# Remind an author, a reviewer or the editor to return to a review after a 
# certain period of time (supported units days and weeks)
@med-oc remind @reviewer in 2 weeks

```

**Comment by max-anu** [comment]
@med-oc code of conduct

**Comment by med-oc** [comment]
Our CoC: https://github.com/openjournals/joss/blob/master/CODE_OF_CONDUCT.md

**Comment by med-oc** [comment]
It's adapted from the Contributor Covenant: http://contributor-covenant.org

**Comment by med-oc** [comment]
Reports of abusive or harassing behavior may be reported to reports@theoj.org

**Comment by max-anu** [comment]
@med-oc test update

**Comment by med-oc** [comment]
blah blah blah blah blah

**Comment by med-oc** [comment]
aaaaa

**Comment by max-anu** [comment]
@med-oc add @max-anu  as reviewer

**Comment by med-oc** [comment]
@max-anu added to the reviewers list!

**Comment by max-anu** [comment]
@med-oc assign @max-anu as editor

**Comment by med-oc** [comment]
Assigned! @max-anu is now the editor

**Comment by max-anu** [comment]
@med-oc add assignee: @max-anu

**Comment by med-oc** [comment]
@max-anu added as assignee.

**Comment by max-anu** [comment]
@med-oc list editors

**Comment by med-oc** [comment]
Current recipe editors

```
@AndyHoggANU
@CodeGat
@MartinDix
@NBateman-bit
@OKaluza
@Quartzer2
@SeanBryan51
@aidanheerdegen
@atteggiani
@bschroeter
@ccarouge
@dougiesquire
@echus
@ezhilsabareesh8
@flicj191
@harshula
@headmetal
@heidinett
@jo-basevi
@kdruken
@kieranricardo
@max-anu
@med-oc
@rbeucher
@rogeredberg
@svenbuder
@utkarshgupta95
```

**Comment by max-anu** [comment]
@med-oc check references

**Comment by max-anu** [comment]
@med-oc check repository

**Comment by max-anu** [comment]
@med-oc set v1.2.3 as version

**Comment by med-oc** [comment]
Done! version is now v1.2.3

**Comment by max-anu** [comment]
@med-oc set 10.21105/joss.12345 as archive

**Comment by med-oc** [comment]
Done! archive is now 10.21105/joss.12345

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
hello @med-oc

**Comment by max-anu** [comment]
hello @med-oc

**Comment by max-anu** [comment]
hello @med-oc

**Comment by med-oc** [comment]
Hi!

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by med-oc** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00007/medportal.00007/10.21105.medportal.00007.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/ACCESS-NRI/med-recipes/blob/medportal.00007/medportal.00007/10.21105.medportal.00007.pdf) :page_facing_up: :point_left:

**Comment by max-anu** [comment]
@med-oc start review

**Comment by max-anu** [comment]
@med-oc start review

**Comment by max-anu** [comment]
hello @med-oc

**Comment by med-oc** [comment]
Hi!

**Comment by max-anu** [comment]
@med-oc start review

**Comment by med-oc** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/10.
