### ISSUE TITLE
[REVIEW]: Example Medportal 2

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#9]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal2
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @max-anu
**Reviewers:** @max-anu
**Archive:** 10.21105/MedPortal.12345

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/1ac357e8f9c0ca329c3b5b2efaf3c90d/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/1ac357e8f9c0ca329c3b5b2efaf3c90d)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/1ac357e8f9c0ca329c3b5b2efaf3c90d"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/1ac357e8f9c0ca329c3b5b2efaf3c90d/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/1ac357e8f9c0ca329c3b5b2efaf3c90d/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/1ac357e8f9c0ca329c3b5b2efaf3c90d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/max-anu/example-medportal2" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@max-anu, your review will be checklist based. Each of you will have a separate checklist that you should update when carrying out your review.
First of all you need to run this command in a separate comment to create the checklist:

```
@med-oc generate my checklist
```

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @max-anu know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Checklists

📝 [Checklist for @max-anu](https://github.com/ACCESS-NRI/med-reviews/issues/9#issuecomment-1679824401)

**Comment by med-oc** [comment]
Hello humans, I'm @med-oc, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@med-oc help
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@med-oc generate pdf
```

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc hi

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc generate my checklist

**Comment by med-oc** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00009/medportal.00009/10.21105.medportal.00009.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/ACCESS-NRI/med-recipes/blob/medportal.00009/medportal.00009/10.21105.medportal.00009.pdf) :page_facing_up: :point_left:

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Blah Blah Blah
@med-oc test update

# Add to this issue's reviewers list
@med-oc add @username as reviewer

# Remove from this issue's reviewers list
@med-oc remove @username from reviewers

# Assign a user as the editor of this submission
@med-oc assign @username as editor

# Remove the editor assigned to this submission
@med-oc remove editor

# Send an invitation to a user to collaborate in the review
@med-oc invite @username

# Add a user to this issue's assignees list
@med-oc add assignee: @username

# Remove a user from this issue's assignees list
@med-oc remove assignee: @username

# Replies to 'list editors'
@med-oc list editors

# Set a value for version
@med-oc set v1.0.0 as version

# Set a value for archive
@med-oc set 10.21105/joss.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@med-oc review successful

# Label issue with: recommend rejection
@med-oc review failed

# Close the issue
@med-oc reject

# Add review checklist for a user
@med-oc add checklist for @username

# Remove the checklist for a user
@med-oc remove checklist for @username

# Generates the pdf paper
@med-oc generate pdf

# Open the review issue
@med-oc start review

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by max-anu** [comment]
@med-oc set 10.21105/joss.12345 as archive

**Comment by med-oc** [comment]
Done! archive is now 10.21105/joss.12345

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Add to this issue's reviewers list
@med-oc add @username as reviewer

# Remove from this issue's reviewers list
@med-oc remove @username from reviewers

# Assign a user as the editor of this submission
@med-oc assign @username as editor

# Remove the editor assigned to this submission
@med-oc remove editor

# Send an invitation to a user to collaborate in the review
@med-oc invite @username

# Add a user to this issue's assignees list
@med-oc add assignee: @username

# Remove a user from this issue's assignees list
@med-oc remove assignee: @username

# Replies to 'list editors'
@med-oc list editors

# Set a value for version
@med-oc set v1.0.0 as version

# Set a value for archive
@med-oc set 10.21105/joss.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@med-oc review successful

# Label issue with: recommend rejection
@med-oc review failed

# Close the issue
@med-oc reject

# Add review checklist for a user
@med-oc add checklist for @username

# Remove the checklist for a user
@med-oc remove checklist for @username

# Generates the pdf paper
@med-oc generate pdf

# Recommends the submission for acceptance
@med-oc recommend-accept

# Generates a LaTeX preprint file
@med-oc generate preprint

# Open the review issue
@med-oc start review

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by med-oc** [comment]
The paper's PDF and metadata files generation produced some warnings that could prevent the final paper from being published. Please fix them before the end of the review process.
```
1\textrm{ else}
^
unexpected control sequence \cr
expecting "%", "\\label", "\\tag", "\\nonumber" or whitespace
```

**Comment by med-oc** [comment]
:warning: [Error preparing paper acceptance](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5874321202?check_suite_focus=true). The generated XML metadata file is invalid. 

```yaml
Element doi: [facet 'pattern'] The value '00.00000/MedPortal.00009' is not accepted by the pattern '10\.[0-9]{4,9}/.{1,200}'.
```

**Comment by max-anu** [comment]
@med-oc set 10.21105/MedPortal.12345 as archive

**Comment by med-oc** [comment]
Done! archive is now 10.21105/MedPortal.12345

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by med-oc** [comment]
The paper's PDF and metadata files generation produced some warnings that could prevent the final paper from being published. Please fix them before the end of the review process.
```
1\textrm{ else}
^
unexpected control sequence \cr
expecting "%", "\\label", "\\tag", "\\nonumber" or whitespace
```

**Comment by med-oc** [comment]
:warning: [Error preparing paper acceptance](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5874331580?check_suite_focus=true). The generated XML metadata file is invalid. 

```yaml
Element doi: [facet 'pattern'] The value '00.00000/MedPortal.00009' is not accepted by the pattern '10\.[0-9]{4,9}/.{1,200}'.
```

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by med-oc** [comment]
The paper's PDF and metadata files generation produced some warnings that could prevent the final paper from being published. Please fix them before the end of the review process.
```
1\textrm{ else}
^
unexpected control sequence \cr
expecting "%", "\\label", "\\tag", "\\nonumber" or whitespace
```

**Comment by med-oc** [comment]
:warning: [Error preparing paper acceptance](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5874567499?check_suite_focus=true). The generated XML metadata file is invalid. 

```yaml
IDREFS attribute rid references an unknown ID "figU003Aexample"
```

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by med-oc** [comment]
The paper's PDF and metadata files generation produced some warnings that could prevent the final paper from being published. Please fix them before the end of the review process.
```
1\textrm{ else}
^
unexpected control sequence \cr
expecting "%", "\\label", "\\tag", "\\nonumber" or whitespace
```

**Comment by med-oc** [comment]
:warning: [Error preparing paper acceptance](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5874836110?check_suite_focus=true). The generated XML metadata file is invalid. 

```yaml
IDREFS attribute rid references an unknown ID "figU003Aexample"
```

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by med-oc** [comment]
The paper's PDF and metadata files generation produced some warnings that could prevent the final paper from being published. Please fix them before the end of the review process.
```
1\textrm{ else}
^
unexpected control sequence \cr
expecting "%", "\\label", "\\tag", "\\nonumber" or whitespace
```

**Comment by med-oc** [comment]
:warning: [Error preparing paper acceptance](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5874910629?check_suite_focus=true). The generated XML metadata file is invalid. 

```yaml
IDREFS attribute rid references an unknown ID "figU003Aexample"
```

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by med-oc** [comment]
:wave: @openjournals/mt-eics, this paper is ready to be accepted and published.

Check final proof :point_right::page_facing_up: [Download article](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00009/medportal.00009/10.21105.medportal.00009.pdf)

If the paper PDF and the deposit XML files look good in https://github.com/ACCESS-NRI/med-recipes/pull/8, then you can now move forward with accepting the submission by compiling again with the command `@editorialbot accept`

**Comment by med-oc** [comment]
:warning: [Error preparing paper acceptance](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5874926258?check_suite_focus=true).

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Add to this issue's reviewers list
@med-oc add @username as reviewer

# Remove from this issue's reviewers list
@med-oc remove @username from reviewers

# Assign a user as the editor of this submission
@med-oc assign @username as editor

# Remove the editor assigned to this submission
@med-oc remove editor

# Send an invitation to a user to collaborate in the review
@med-oc invite @username

# Add a user to this issue's assignees list
@med-oc add assignee: @username

# Remove a user from this issue's assignees list
@med-oc remove assignee: @username

# Replies to 'list editors'
@med-oc list editors

# Set a value for version
@med-oc set v1.0.0 as version

# Set a value for archive
@med-oc set 10.21105/joss.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@med-oc review successful

# Label issue with: recommend rejection
@med-oc review failed

# Close the issue
@med-oc reject

# Add review checklist for a user
@med-oc add checklist for @username

# Remove the checklist for a user
@med-oc remove checklist for @username

# Generates the pdf paper
@med-oc generate pdf

# Recommends the submission for acceptance
@med-oc recommend-accept

# Generates a LaTeX preprint file
@med-oc generate preprint

# Open the review issue
@med-oc start review

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by med-oc** [comment]
:wave: @openjournals/mt-eics, this paper is ready to be accepted and published.

Check final proof :point_right::page_facing_up: [Download article](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00009/medportal.00009/10.21105.medportal.00009.pdf)

If the paper PDF and the deposit XML files look good in https://github.com/ACCESS-NRI/med-recipes/pull/9, then you can now move forward with accepting the submission by compiling again with the command `@editorialbot accept`

**Comment by med-oc** [comment]
:warning: [Error preparing paper acceptance](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5874961681?check_suite_focus=true).

**Comment by max-anu** [comment]
@med-oc recommend-accept

**Comment by med-oc** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by med-oc** [comment]
:wave: @openjournals/mt-eics, this paper is ready to be accepted and published.

Check final proof :point_right::page_facing_up: [Download article](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00009/medportal.00009/10.21105.medportal.00009.pdf)

If the paper PDF and the deposit XML files look good in https://github.com/ACCESS-NRI/med-recipes/pull/10, then you can now move forward with accepting the submission by compiling again with the command `@editorialbot accept`

**Comment by max-anu** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @max-anu, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Add to this issue's reviewers list
@med-oc add @username as reviewer

# Remove from this issue's reviewers list
@med-oc remove @username from reviewers

# Assign a user as the editor of this submission
@med-oc assign @username as editor

# Remove the editor assigned to this submission
@med-oc remove editor

# Send an invitation to a user to collaborate in the review
@med-oc invite @username

# Add a user to this issue's assignees list
@med-oc add assignee: @username

# Remove a user from this issue's assignees list
@med-oc remove assignee: @username

# Replies to 'list editors'
@med-oc list editors

# Set a value for version
@med-oc set v1.0.0 as version

# Set a value for archive
@med-oc set 10.21105/joss.12345 as archive

# Label issue with: reviewed, recommend publication, pending publication. Remove labels: ongoing, pending review
@med-oc review successful

# Label issue with: recommend rejection
@med-oc review failed

# Close the issue
@med-oc reject

# Add review checklist for a user
@med-oc add checklist for @username

# Remove the checklist for a user
@med-oc remove checklist for @username

# Generates the pdf paper
@med-oc generate pdf

# Recommends the submission for acceptance
@med-oc recommend-accept

# Generates a LaTeX preprint file
@med-oc generate preprint

# Open the review issue
@med-oc start review

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by max-anu** [comment]
@med-oc accept

**Comment by med-oc** [comment]
I'm sorry @max-anu, I'm afraid I can't do that. That's something only eics are allowed to do.

**Comment by max-anu** [comment]
@med-oc generate preprint

**Comment by med-oc** [comment]
:warning: [An error happened when generating the LaTeX preprint file](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5875044275?check_suite_focus=true).

**Comment by max-anu** [comment]
@med-oc accept

**Comment by med-oc** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by med-oc** [comment]
:warning: Couldn't acccept/publish paper. [An error happened](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5875120554?check_suite_focus=true).

**Comment by max-anu** [comment]
@med-oc accept

**Comment by med-oc** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by med-oc** [comment]
:warning: Couldn't acccept/publish paper. [An error happened](https://github.com/ACCESS-NRI/med-recipes/actions/runs/5897532181?check_suite_focus=true).
