### ISSUE TITLE
[PRE REVIEW]: Introduction to the ACCESS-NRI Intake catalog

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#91]
**Submitting author:** @rbeucher (<a href="http://orcid.org/0000-0003-3891-5444">Romain Beucher</a>)
**Repository:** https://github.com/rbeucher/med-portal-intake-tutorial.git
**Branch with paper.md** (empty if default branch): 
**Version:** v0.0.1
**Editor:** @rbeucher
**Reviewers:** @rbeucher
**Managing EiC:** Romain Beucher

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/6be53a768a72a21e1c92012153ba0329/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/6be53a768a72a21e1c92012153ba0329)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/6be53a768a72a21e1c92012153ba0329"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/6be53a768a72a21e1c92012153ba0329/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/6be53a768a72a21e1c92012153ba0329/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/6be53a768a72a21e1c92012153ba0329)
```

**Author instructions**

Thanks for submitting your recipe to medportal @rbeucher. **Currently, there isn't a medportal editor assigned** to your recipe.

The AEiC suggestion for the handling editor is @max-anu.

@rbeucher if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). You can search [the list of people](https://reviewers.medportal-dev-6a745f452687.herokuapp.com/lookup) that have already agreed to review and may be suitable for this submission.

**Editor instructions**

The medportal submission bot @med-oc is here to help you find and assign reviewers and start the main review. To find out what @med-oc can do for you type:

```
@med-oc commands
```

**Comment by med-oc** [comment]
Hello humans, I'm @med-oc, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@med-oc help
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@med-oc generate pdf
```

**Comment by rbeucher** [comment]
@med-oc add @max-anu as reviewer

**Comment by med-oc** [comment]
I'm sorry @rbeucher, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by max-anu** [comment]
@med-oc add @rbeucher  as reviewer

**Comment by med-oc** [comment]
@rbeucher added to the reviewers list!

**Comment by max-anu** [comment]
@med-oc assign @rbeucher as editor

**Comment by med-oc** [comment]
Assigned! @rbeucher is now the editor

**Comment by max-anu** [comment]
@med-oc create draft

**Comment by med-oc** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@med-oc help`

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by med-oc** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00091/medportal.00091/10.21105.medportal.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/ACCESS-NRI/med-recipes/blob/medportal.00091/medportal.00091/10.21105.medportal.00091.pdf) :page_facing_up: :point_left:

**Comment by rbeucher** [comment]
@med-oc generate pdf

**Comment by rbeucher** [comment]
@med-oc generate pdf

**Comment by rbeucher** [comment]
@med-oc help

**Comment by med-oc** [comment]
Hello @rbeucher, here are the things you can ask me to do:

```

# List all available commands
@med-oc help

# Show our community Code of Conduct and Guidelines
@med-oc code of conduct

# Replies to 'list editors'
@med-oc list editors

# Add review checklist for a user
@med-oc add checklist for @username

# Remove the checklist for a user
@med-oc remove checklist for @username

# Generates the pdf paper
@med-oc generate pdf

# Generates a LaTeX preprint file
@med-oc generate preprint

# Adds a checklist for the reviewer using this command
@med-oc generate my checklist

```

**Comment by rbeucher** [comment]
@med-oc list editors

**Comment by med-oc** [comment]
Current recipe editors

```
@AndyHoggANU
@CodeGat
@MartinDix
@NBateman-bit
@OKaluza
@Quartzer2
@SeanBryan51
@aidanheerdegen
@atteggiani
@bschroeter
@ccarouge
@dougiesquire
@echus
@ezhilsabareesh8
@flicj191
@harshula
@headmetal
@heidinett
@jo-basevi
@kdruken
@kieranricardo
@max-anu
@med-oc
@rbeucher
@rogeredberg
@svenbuder
@utkarshgupta95
```

**Comment by rbeucher** [comment]
@med-oc generate pdf

**Comment by rbeucher** [comment]
@max-anu it does not seem to work for me...

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by med-oc** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00091/medportal.00091/10.21105.medportal.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/ACCESS-NRI/med-recipes/blob/medportal.00091/medportal.00091/10.21105.medportal.00091.pdf) :page_facing_up: :point_left:

**Comment by max-anu** [comment]
it works for me?

**Comment by rbeucher** [comment]
Yes it works for you... special treatment

**Comment by rbeucher** [comment]
@med-oc generate pdf

**Comment by med-oc** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00091/medportal.00091/10.21105.medportal.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/ACCESS-NRI/med-recipes/blob/medportal.00091/medportal.00091/10.21105.medportal.00091.pdf) :page_facing_up: :point_left:

**Comment by rbeucher** [comment]
@med-oc generate pdf

**Comment by rbeucher** [comment]
@med-oc generate pdf

**Comment by rbeucher** [comment]
@med-oc generate pdf

**Comment by rbeucher** [comment]
@med-oc generate pdf

**Comment by max-anu** [comment]
@med-oc generate pdf

**Comment by med-oc** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/medportal.00091/medportal.00091/10.21105.medportal.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/ACCESS-NRI/med-recipes/blob/medportal.00091/medportal.00091/10.21105.medportal.00091.pdf) :page_facing_up: :point_left:

**Comment by max-anu** [comment]
@med-oc start review

**Comment by med-oc** [comment]
OK, I've started the review over in https://github.com/ACCESS-NRI/med-reviews/issues/92.
